/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author joel
 */
public class CrearTablero extends javax.swing.JFrame {

    private int numeroColumnas;
    private int numeroFilas;
    private int tamX;
    private int tamY;
    private JButton[][] MatrizBotones;

    public CrearTablero(int noColumnas, int noFilas) {
        numeroColumnas = noColumnas;
        numeroFilas = noFilas;
        initComponents();
        this.setLocationRelativeTo(null);
        iniciarMatrix();
    }


    public void iniciarMatrix() {
        MatrizBotones = new JButton[numeroFilas][numeroColumnas];
        panelBotonesjPanel.setLayout(new GridLayout(numeroFilas, numeroColumnas));

        //Se obtiene el tamaño de los botones acorde a su cantidad
        tamañoBotones(numeroFilas, numeroColumnas);

        for (int i = 0; i < numeroFilas; i++) {
            for (int j = 0; j < numeroColumnas; j++) {
                JButton botonNuevo = new JButton();
                botonNuevo.setSize(tamX, tamY);
                //Se agrega a la matriz el botón recien creado
                MatrizBotones[i][j] = botonNuevo;
                MatrizBotones[i][j].setBackground(java.awt.Color.white);

                MatrizBotones[i][j].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        for (int i = 0; i < numeroFilas; i++) {
                            for (int j = 0; j < numeroColumnas; j++) {
                                if (e.getSource().equals(MatrizBotones[i][j])) {
                                    MatrizBotones[i][j].setBackground(java.awt.Color.black);
                                    MatrizBotones[i][j].setName("1");
                                    return;

                                }
                            }
                        }
                    }
                });

                MatrizBotones[i][j].addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        if (SwingUtilities.isRightMouseButton(e)) {

                            for (int i = 0; i < numeroFilas; i++) {
                                for (int j = 0; j < numeroColumnas; j++) {
                                    if (e.getSource().equals(MatrizBotones[i][j])) {

                                        MatrizBotones[i][j].setBackground(java.awt.Color.white);
                                        MatrizBotones[i][j].setName("0");
                                        return;
                                    }
                                }

                            }
                        }
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        
                    }
                });

                panelBotonesjPanel.add(MatrizBotones[i][j]);
            }
        }
    }

    private void tamañoBotones(int cantX, int cantY) {
        tamX = panelBotonesjPanel.getWidth() / cantX;
        tamY = panelBotonesjPanel.getHeight() / cantY;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelBotonesjPanel = new javax.swing.JPanel();
        textoDiseñoPreviojLabel = new javax.swing.JLabel();
        fondoDiseñojLabel = new javax.swing.JLabel();

        jButton9.setText("jButton9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBotonesjPanel.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.add(panelBotonesjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 620));

        textoDiseñoPreviojLabel.setBackground(new java.awt.Color(255, 255, 204));
        textoDiseñoPreviojLabel.setFont(new java.awt.Font("DejaVu Serif", 1, 48)); // NOI18N
        textoDiseñoPreviojLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoDiseñoPreviojLabel.setText("Diseño Previo");
        jPanel1.add(textoDiseñoPreviojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 380, 70));

        fondoDiseñojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TableroMonopoly.png"))); // NOI18N
        jPanel1.add(fondoDiseñojLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1170, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoDiseñojLabel;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotonesjPanel;
    private javax.swing.JLabel textoDiseñoPreviojLabel;
    // End of variables declaration//GEN-END:variables
}
